services:
  mongo:
    image: mongo:6.0
    container_name: fastbite-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fastbite
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- NUEVO: Tu aplicación descargada de Docker Hub ---
  app:
    image: noru08/fastbite:latest  # <--- ¡Aquí está la magia!
    container_name: fastbite-app
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      # IMPORTANTE: Sobrescribimos 'localhost' por 'mongo' para que se hablen entre contenedores
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/fastbite

volumes:
  mongo-data:
