spring:
  application:
    name: fastbite

  data:
    mongodb:
      auto-index-creation: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mongodb:
    uri: mongodb://localhost:27017/fastbite

server:
  port: 8080

# JWT Configuration (hardcodeado)
jwt:
  secret: m3xOhI2Jur8FQZqyFsu4sKINakePXZCuQFBRot4Bvhc=
  expiration: 86400000  # 24 hours in milliseconds

# Logging
logging:
  level:
    org.springframework.security: DEBUG
    com.fastbite: DEBUG