spring:
  application:
    name: user-service
    mongodb:
      uri: mongodb://localhost:27017/fastbite-users

server:
  port: 8081

jwt:
  secret: fastbite-super-secret-key-that-should-be-at-least-256-bits-long-for-hs256
  expiration: 86400000